package com.manliao.backend.live;
import java.util.*;
import java.time.*;
import java.sql.Timestamp;
import java.security.*;
import java.nio.charset.StandardCharsets;
import org.springframework.stereotype.Service;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.support.TransactionTemplate;
import tools.jackson.databind.ObjectMapper;
import com.manliao.backend.common.*;
import com.manliao.backend.identity.AuthDtos.Principal;
import com.manliao.backend.profiles.ProfileTextReview;
import com.manliao.backend.admin.*;
@Service
public class LivePreflightService {
 private final JdbcTemplate db;private final TransactionTemplate tx;private final LiveRoomService rooms;private final HostVerificationService hosts;private final ProfileTextReview review;private final ObjectMapper json;private final DatabaseRows rows;private final AdminService admins;
 public LivePreflightService(JdbcTemplate db,TransactionTemplate tx,LiveRoomService rooms,HostVerificationService hosts,ProfileTextReview review,ObjectMapper json,DatabaseRows rows,AdminService admins){this.db=db;this.tx=tx;this.rooms=rooms;this.hosts=hosts;this.review=review;this.json=json;this.rows=rows;this.admins=admins;}
 private String hash(String value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)));}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
 private void content(Map<String,Object> room,Map<String,Object> checks,List<String> failures,List<String> warnings){
  var labels=review.labels(room.get("title")+" "+room.get("category")+" "+room.get("tags"));checks.put("text_moderation",Map.of("status",labels.isEmpty()?"passed":"failed","provider","local_rules","labels",labels));if(!labels.isEmpty())failures.add("live_text_rejected");
  String cover=(String)room.get("cover_url");if(cover==null||cover.isBlank()){checks.put("cover",Map.of("status","warning","reason","cover_missing"));warnings.add("cover_missing");return;}
  var assets=db.queryForList("SELECT id,status,processing_status FROM media_assets WHERE owner_user_id=? AND url=? AND media_type='image' AND source='profile'",room.get("host_user_id"),cover);String failure=null;
  if(assets.isEmpty())failure="cover_not_owned";else if(!"approved".equals(assets.getFirst().get("status")))failure="cover_"+assets.getFirst().get("status");else if(!"ready".equals(assets.getFirst().get("processing_status")))failure="cover_processing";
  if(failure!=null){failures.add(failure);checks.put("cover",Map.of("status","failed","reason",failure));}else checks.put("cover",Map.of("status","passed","media_asset_id",assets.getFirst().get("id")));
 }
 private Map<String,Object> output(Map<String,Object> r,String ticket,boolean admin){var out=rows.output(r,"checks","failure_codes","warning_codes");out.remove("ticket_hash");var failures=json.readTree(r.get("failure_codes").toString());var warnings=json.readTree(r.get("warning_codes").toString());boolean confirmation=false;for(var w:warnings)if(Set.of("network_metrics_missing","network_latency_high","network_upload_low").contains(w.asString())&&!Boolean.TRUE.equals(r.get("user_confirmed_warnings")))confirmation=true;out.put("requires_confirmation",confirmation);out.put("can_start",failures.isEmpty()&&!confirmation&&r.get("consumed_at")==null&&r.get("expires_at")!=null&&((Timestamp)r.get("expires_at")).toInstant().isAfter(Instant.now()));out.put("ticket",ticket);if(!admin)for(String key:List.of("app_version","camera_permission","microphone_permission","camera_available","microphone_available","network_type","latency_ms","upload_mbps"))out.remove(key);return out;}
 public Map<String,Object> check(Principal actor,String id,LiveRoomController.Preflight input){return tx.execute(s->{var r=rooms.lock(actor,id);rooms.owner(actor,r);if(!"draft".equals(r.get("status")))throw new ApiError(409,"LIVE_ROOM_STATE_INVALID","只有草稿可以执行开播检查");hosts.assertCanStart(actor.userId());
  var checks=new LinkedHashMap<String,Object>();var failures=new ArrayList<String>();var warnings=new ArrayList<String>();String[] names={"camera_permission","microphone_permission","camera_available","microphone_available"},codes={"camera_permission_denied","microphone_permission_denied","camera_unavailable","microphone_unavailable"};boolean[] values={input.camera_permission(),input.microphone_permission(),input.camera_available(),input.microphone_available()};for(int i=0;i<4;i++){checks.put(names[i],Map.of("status",values[i]?"passed":"failed"));if(!values[i])failures.add(codes[i]);}
  boolean active=db.queryForObject("SELECT count(*) FROM live_rooms WHERE host_user_id=? AND status='live'",Integer.class,actor.userId())>0;checks.put("active_room",Map.of("status",active?"failed":"passed"));if(active)failures.add("host_already_live");content(r,checks,failures,warnings);
  String network="passed";if(input.network_type().equals("none")){failures.add("network_unavailable");network="failed";}else if(input.latency_ms()==null||input.upload_mbps()==null){warnings.add("network_metrics_missing");network="warning";}else{
   if(input.latency_ms()>=800){failures.add("network_latency_critical");network="failed";}else if(input.latency_ms()>=300){warnings.add("network_latency_high");network="warning";}
   if(input.upload_mbps()<1){failures.add("network_upload_critical");network="failed";}else if(input.upload_mbps()<3){warnings.add("network_upload_low");if(!network.equals("failed"))network="warning";}
  }
  var net=new LinkedHashMap<String,Object>();net.put("status",network);net.put("type",input.network_type());net.put("latency_ms",input.latency_ms());net.put("upload_mbps",input.upload_mbps());checks.put("network",net);
  try{rooms.available((String)r.get("stream_provider"));checks.put("provider",Map.of("status","passed","provider",r.get("stream_provider")));}catch(ApiError unavailable){failures.add("live_provider_unavailable");checks.put("provider",Map.of("status","failed","provider",r.get("stream_provider")));}
  boolean confirmation=warnings.stream().anyMatch(w->w.startsWith("network_"))&&!input.user_confirmed_warnings();String ticket=failures.isEmpty()&&!confirmation?Base64.getUrlEncoder().withoutPadding().encodeToString(new SecureRandom().generateSeed(40)):null;String check=LiveRoomService.id("live_preflight");
  // A new check invalidates previous unconsumed tickets, including when the new check fails.
  db.update("UPDATE live_start_preflights SET expires_at=clock_timestamp() WHERE room_id=? AND consumed_at IS NULL AND ticket_hash IS NOT NULL",id);
  db.update("INSERT INTO live_start_preflights(id,room_id,host_user_id,device_id,app_version,camera_permission,microphone_permission,camera_available,microphone_available,network_type,latency_ms,upload_mbps,provider,result,checks,failure_codes,warning_codes,user_confirmed_warnings,ticket_hash,expires_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?::jsonb,?::jsonb,?::jsonb,?,?,?)",check,id,actor.userId(),input.device_id().strip(),input.app_version(),input.camera_permission(),input.microphone_permission(),input.camera_available(),input.microphone_available(),input.network_type(),input.latency_ms(),input.upload_mbps(),r.get("stream_provider"),!failures.isEmpty()?"failed":warnings.isEmpty()?"passed":"warning",json.writeValueAsString(checks),json.writeValueAsString(failures),json.writeValueAsString(warnings),input.user_confirmed_warnings(),ticket==null?null:hash(ticket),ticket==null?null:Timestamp.from(Instant.now().plusSeconds(300)));return output(db.queryForMap("SELECT * FROM live_start_preflights WHERE id=?",check),ticket,false);
 });}
 public Map<String,Object> start(Principal actor,String id,String ticket){return tx.execute(s->{var r=rooms.lock(actor,id);rooms.owner(actor,r);if(!"draft".equals(r.get("status")))throw LiveRoomService.state("只有草稿直播间可以开播");hosts.assertCanStart(actor.userId());rooms.available((String)r.get("stream_provider"));if(ticket==null||ticket.isBlank())throw new ApiError(403,"LIVE_PREFLIGHT_REQUIRED","请先完成设备与网络检查");var checks=db.queryForList("SELECT * FROM live_start_preflights WHERE room_id=? AND host_user_id=? AND ticket_hash=? FOR UPDATE",id,actor.userId(),hash(ticket));if(checks.isEmpty())throw new ApiError(403,"LIVE_PREFLIGHT_INVALID","开播票据无效");var check=checks.getFirst();if(check.get("consumed_at")!=null)throw new ApiError(409,"LIVE_PREFLIGHT_INVALID","开播票据已使用");if(check.get("expires_at")==null||!((Timestamp)check.get("expires_at")).toInstant().isAfter(Instant.now()))throw new ApiError(403,"LIVE_PREFLIGHT_INVALID","开播票据已过期");
  var failures=new ArrayList<String>();content(r,new HashMap<>(),failures,new ArrayList<>());if(!failures.isEmpty())throw new ApiError(403,"LIVE_PREFLIGHT_FAILED","开播内容状态已变化，请重新检查");rooms.activate(actor,id);db.update("UPDATE live_start_preflights SET result='consumed',consumed_at=clock_timestamp() WHERE id=?",check.get("id"));return rooms.output(rooms.room(id,false));
 });}
 public List<Map<String,Object>> list(AdminDtos.Principal actor,String result,String host,String room){admins.require(actor,"live_preflight.read",false);return db.queryForList("SELECT * FROM live_start_preflights WHERE (?::text IS NULL OR result=?) AND (?::text IS NULL OR host_user_id=?) AND (?::text IS NULL OR room_id=?) ORDER BY created_at DESC,id DESC LIMIT 200",result,result,host,host,room,room).stream().map(r->output(r,null,true)).toList();}
}
