package com.manliao.backend.live;
import java.util.*;
import java.time.*;
import java.sql.Timestamp;
import org.springframework.stereotype.Service;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.support.TransactionTemplate;
import com.manliao.backend.identity.AuthDtos.Principal;
import com.manliao.backend.common.*;
import com.manliao.backend.billing.*;
import com.manliao.backend.gifts.GiftSafetyService;
import com.manliao.backend.admin.*;
import com.manliao.backend.media.MediaService;
@Service
public class LiveGiftService {
 private final JdbcTemplate db;private final TransactionTemplate tx;private final LiveRoomService rooms;private final HostVerificationService hosts;private final GiftSafetyService safety;private final WalletService wallet;private final LedgerService ledger;private final DatabaseRows rows;private final AdminService admin;private final MediaService media;
 public LiveGiftService(JdbcTemplate db,TransactionTemplate tx,LiveRoomService rooms,HostVerificationService hosts,GiftSafetyService safety,WalletService wallet,LedgerService ledger,DatabaseRows rows,AdminService admin,MediaService media){this.db=db;this.tx=tx;this.rooms=rooms;this.hosts=hosts;this.safety=safety;this.wallet=wallet;this.ledger=ledger;this.rows=rows;this.admin=admin;this.media=media;}
 private record Outcome(Map<String,Object> value,ApiError error){}
 private Map<String,Object> deliver(Outcome result){if(result.error()!=null)throw result.error();return result.value();}
 private Outcome ok(Map<String,Object> value){return new Outcome(value,null);}
 private Outcome denied(String user,String room,String type,String severity,long amount,int status,String code,String message,Map<String,Object> details){safety.record(user,room,type,severity,"open",amount,details);return new Outcome(null,new ApiError(status,code,message));}
 private Map<String,Object> access(Principal actor,String id,boolean sending){var r=rooms.lock(actor,id);if(!"live".equals(r.get("status")))throw LiveRoomService.state("当前直播间未开播");if(!"active".equals(rooms.member(id,actor.userId()).get("presence_status")))throw new ApiError(400,"LIVE_ROOM_MANAGE_FORBIDDEN","请先进入直播间");if(sending){if(actor.userId().equals(r.get("host_user_id")))throw new ApiError(400,"LIVE_ROOM_MANAGE_FORBIDDEN","主播不能给自己送礼");hosts.assertCanReceive((String)r.get("host_user_id"));}return r;}
 private Map<String,Object> gift(String code){var found=db.queryForList("SELECT * FROM live_gift_catalog_items WHERE code=? AND status='active' FOR SHARE",code.strip().toLowerCase(Locale.ROOT));if(found.isEmpty())throw new ApiError(404,"COMMON_NOT_FOUND","礼物不存在或已下架");return found.getFirst();}
 private long n(Map<String,Object> row,String field){return ((Number)row.get(field)).longValue();}
 private Outcome limits(Principal actor,String room,long amount,Map<String,Object> setting){
  if("minor".equals(setting.get("age_status")))return denied(actor.userId(),room,"minor_gifting_blocked","critical",amount,403,"LIVE_GIFT_MINOR_FORBIDDEN","未成年用户不能参与直播打赏",Map.of());
  if(Boolean.TRUE.equals(setting.get("age_verification_required"))&&!"adult".equals(setting.get("age_status")))return denied(actor.userId(),room,"age_verification_required","high",amount,403,"LIVE_GIFT_AGE_VERIFICATION_REQUIRED","请先完成年龄核验",Map.of());
  if(amount>n(setting,"effective_single_limit_coins"))return denied(actor.userId(),room,"single_limit_exceeded","high",amount,409,"LIVE_GIFT_LIMIT_EXCEEDED","超过单笔限额",Map.of("single_limit_coins",setting.get("effective_single_limit_coins")));
  if(amount>n(setting,"today_remaining_coins"))return denied(actor.userId(),room,"daily_limit_exceeded","high",amount,409,"LIVE_GIFT_LIMIT_EXCEEDED","超过单日限额",Map.of("daily_limit_coins",setting.get("effective_daily_limit_coins"),"today_spent_coins",setting.get("today_spent_coins")));return null;
 }
 private Map<String,Object> output(Map<String,Object> row){var out=rows.output(row);out.remove("client_request_id");return out;}
 public Map<String,Object> confirmation(Principal actor,String room,LiveGiftController.Confirm input){return deliver(tx.execute(s->{access(actor,room,true);var gift=gift(input.gift_code());long amount=n(gift,"price_coins")*input.quantity();var blocked=limits(actor,room,amount,safety.get(actor));if(blocked!=null)return blocked;String id=LiveRoomService.id("gift_confirmation");db.update("INSERT INTO gift_risk_confirmations(id,user_id,room_id,gift_code,quantity,total_coins,expires_at) VALUES(?,?,?,?,?,?,now()+interval '5 minutes')",id,actor.userId(),room,gift.get("code"),input.quantity(),amount);return ok(rows.output(db.queryForMap("SELECT id,room_id,gift_code,quantity,total_coins,expires_at FROM gift_risk_confirmations WHERE id=?",id)));}));}
 public Map<String,Object> send(Principal actor,String room,LiveGiftController.Send input){return deliver(tx.execute(s->{
  var r=access(actor,room,true);String request=input.client_request_id().strip(),code=input.gift_code().strip().toLowerCase(Locale.ROOT);if(request.length()<8)throw new ApiError(422,"COMMON_VALIDATION_ERROR","请求号过短");
  var previous=db.queryForList("SELECT * FROM live_gift_records WHERE sender_id=? AND client_request_id=?",actor.userId(),request);if(!previous.isEmpty()){var old=previous.getFirst();if(!room.equals(old.get("room_id"))||!code.equals(old.get("gift_code"))||input.quantity()!=n(old,"quantity")||(input.combo_id()!=null&&!input.combo_id().strip().equals(old.get("combo_id"))))throw new ApiError(409,"BILLING_IDEMPOTENCY_CONFLICT","同一请求号不能用于不同送礼参数");return ok(output(old));}
  var gift=gift(code);long amount=n(gift,"price_coins")*input.quantity();var settings=safety.get(actor);var blocked=limits(actor,room,amount,settings);if(blocked!=null)return blocked;
  int hits=db.queryForObject("INSERT INTO auth_rate_windows(bucket_key,hits,expires_at) VALUES(?,1,now()+interval '10 seconds') ON CONFLICT(bucket_key) DO UPDATE SET hits=CASE WHEN auth_rate_windows.expires_at<=now() THEN 1 ELSE auth_rate_windows.hits+1 END,expires_at=CASE WHEN auth_rate_windows.expires_at<=now() THEN now()+interval '10 seconds' ELSE auth_rate_windows.expires_at END RETURNING hits",Integer.class,"live-gift:"+actor.userId());if(hits>10)return denied(actor.userId(),room,"rapid_gifting","high",amount,429,"LIVE_GIFT_RATE_LIMITED","送礼过于频繁",Map.of("window_count",hits));
  String combo=input.combo_id()==null?LiveRoomService.id("gift_combo"):input.combo_id().strip();if(combo.length()<8)throw new ApiError(422,"COMMON_VALIDATION_ERROR","连击号过短");int comboCount=input.quantity();var combos=db.queryForList("SELECT * FROM live_gift_records WHERE sender_id=? AND combo_id=? ORDER BY created_at DESC,id DESC LIMIT 1",actor.userId(),combo);
  if(!combos.isEmpty()){var old=combos.getFirst();if(!room.equals(old.get("room_id"))||!code.equals(old.get("gift_code"))||((Timestamp)old.get("combo_expires_at")).toInstant().isBefore(Instant.now()))throw new ApiError(409,"COMMON_VALIDATION_ERROR","礼物连击不匹配或已过期");comboCount+=((Number)old.get("combo_count")).intValue();}
  if(comboCount>100)return denied(actor.userId(),room,"combo_limit_exceeded","medium",amount,409,"LIVE_GIFT_COMBO_LIMIT_EXCEEDED","连击已达到上限",Map.of("combo_count",comboCount));
  String confirmation=null;if(amount>=n(settings,"high_value_confirmation_threshold_coins")){var confirmations=db.queryForList("SELECT * FROM gift_risk_confirmations WHERE id=? AND user_id=? AND room_id=? AND gift_code=? AND quantity=? AND total_coins=? AND used_at IS NULL AND expires_at>now() FOR UPDATE",input.risk_confirmation_id(),actor.userId(),room,code,input.quantity(),amount);if(confirmations.isEmpty())return new Outcome(null,new ApiError(409,"LIVE_GIFT_CONFIRMATION_REQUIRED","高额礼物需要二次确认"));confirmation=(String)confirmations.getFirst().get("id");}
  var funds=ledger.ensureWallet(actor.userId());if(n(funds,"balance")<amount)return new Outcome(null,new ApiError(403,"WALLET_INSUFFICIENT_BALANCE","金币余额不足"));
  String id=LiveRoomService.id("live_gift"),host=(String)r.get("host_user_id");long income=amount*7/10; // Exact integer 70%, rounded down once per gift request.
  db.update("""
   INSERT INTO live_gift_records(id,room_id,sender_id,host_user_id,gift_code,gift_name,gift_icon_url,gift_animation_url,gift_renderer_type,gift_animation_checksum,gift_animation_file_size,gift_min_client_version,gift_presentation_tier,gift_animation_duration_ms,combo_id,combo_count,combo_expires_at,is_high_value,unit_price,quantity,total_coins,host_income_coins,client_request_id)
   VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,now()+interval '5 seconds',?,?,?,?,?,?)
   """,id,room,actor.userId(),host,code,gift.get("name"),gift.get("icon_url"),gift.get("animation_url"),gift.get("renderer_type"),gift.get("animation_checksum"),gift.get("animation_file_size"),gift.get("min_client_version"),gift.get("presentation_tier"),gift.get("animation_duration_ms"),combo,comboCount,amount>=520||"fullscreen".equals(gift.get("presentation_tier")),gift.get("price_coins"),input.quantity(),amount,income,request);
  var legs=new ArrayList<LedgerService.Leg>();legs.add(LedgerService.spendable(actor.userId(),-amount,"sender_charge"));if(income>0)legs.add(new LedgerService.Leg("user",host,"host_payable",income,"host_pending_income"));legs.add(LedgerService.platform("platform_gift_revenue",amount-income,"platform_gift_revenue"));
  var posted=ledger.post(new LedgerService.Posting("live-gift:"+actor.userId()+":"+request,"gift_charge",amount,legs,actor.userId(),"live_gift",id,Map.of("room_id",room,"gift_code",code,"quantity",input.quantity(),"host_user_id",host),null,"gift_charge","直播间礼物："+gift.get("name")+" x"+input.quantity()));db.update("UPDATE live_gift_records SET billing_transaction_id=? WHERE id=?",posted.id(),id);db.update("UPDATE live_rooms SET heat=heat+?,updated_at=clock_timestamp() WHERE id=?",amount,room);
  if(confirmation!=null){db.update("UPDATE gift_risk_confirmations SET used_at=clock_timestamp() WHERE id=?",confirmation);String event=safety.record(actor.userId(),room,"high_value_confirmed","info","confirmed",amount,Map.of("confirmation_id",confirmation,"gift_code",code));db.update("UPDATE gift_risk_events SET gift_record_id=? WHERE id=?",id,event);}
  return ok(output(db.queryForMap("SELECT * FROM live_gift_records WHERE id=?",id)));
 }));}
 public List<Map<String,Object>> list(Principal actor,String room,int limit){if(limit<1||limit>100)throw new ApiError(422,"COMMON_VALIDATION_ERROR","分页数量无效");return tx.execute(s->{access(actor,room,false);var records=new ArrayList<>(db.queryForList("SELECT * FROM live_gift_records WHERE room_id=? ORDER BY created_at DESC,id DESC LIMIT ?",room,limit));Collections.reverse(records);return records.stream().map(this::output).toList();});}
 public List<Map<String,Object>> adminList(AdminDtos.Principal actor,String room){admin.require(actor,"live.read",false);rooms.room(room,false);return db.queryForList("SELECT * FROM live_gift_records WHERE room_id=? ORDER BY created_at DESC,id DESC LIMIT 500",room).stream().map(this::output).toList();}
 public List<Map<String,Object>> ranking(Principal actor,String room,int limit){if(limit<1||limit>50)throw new ApiError(422,"COMMON_VALIDATION_ERROR","榜单数量无效");return tx.execute(s->{access(actor,room,false);var out=new ArrayList<Map<String,Object>>();for(var r:db.queryForList("SELECT sender_id,sum(total_coins) AS total_coins,sum(quantity) AS gift_count,max(created_at) AS last_gift_at FROM live_gift_records WHERE room_id=? AND refunded_at IS NULL GROUP BY sender_id ORDER BY sum(total_coins) DESC,max(created_at),sender_id LIMIT ?",room,limit)){String user=(String)r.get("sender_id");boolean own=user.equals(actor.userId());var visible=db.queryForList("SELECT u.nickname,p.avatar_url FROM users u LEFT JOIN user_profiles p ON p.user_id=u.id LEFT JOIN gift_safety_settings s ON s.user_id=u.id WHERE u.id=? AND u.status='active' AND (? OR coalesce(s.ranking_consent,false))",user,own);var item=rows.output(r);item.put("rank",out.size()+1);item.put("is_current_user",own);item.put("sender_id",visible.isEmpty()?"":user);item.put("sender_nickname",visible.isEmpty()?"匿名用户":visible.getFirst().get("nickname"));item.put("sender_avatar_url",visible.isEmpty()?null:media.profileUrl((String)visible.getFirst().get("avatar_url")));out.add(item);}return out;});}
 private void mature(String user){db.update("UPDATE live_gift_records SET income_status='available' WHERE host_user_id=? AND income_status='pending' AND settlement_id IS NULL AND created_at<=now()-interval '7 days'",user);}
 public Map<String,Object> summary(Principal actor){return tx.execute(s->{wallet.lock(actor);mature(actor.userId());var out=new LinkedHashMap<String,Object>();out.put("host_user_id",actor.userId());out.put("release_delay_days",7);long total=0;for(String status:List.of("pending","available","processing","settled")){long amount=db.queryForObject("SELECT coalesce(sum(host_income_coins),0) FROM live_gift_records WHERE host_user_id=? AND income_status=?",Long.class,actor.userId(),status);out.put(status+"_coins",amount);total+=amount;}out.put("total_income_coins",total);return out;});}
 public List<Map<String,Object>> income(Principal actor,String status){if(status!=null&&!Set.of("pending","available","processing","settled").contains(status))throw new ApiError(400,"COMMON_VALIDATION_ERROR","收益状态无效");return tx.execute(s->{wallet.lock(actor);mature(actor.userId());return db.queryForList("SELECT * FROM live_gift_records WHERE host_user_id=? AND (?::text IS NULL OR income_status=?) ORDER BY created_at DESC,id DESC",actor.userId(),status,status).stream().map(this::output).toList();});}
}
