package com.manliao.backend;
import java.net.*;
import java.net.http.*;
import java.util.*;
import java.util.concurrent.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.*;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.support.TransactionTemplate;
import tools.jackson.databind.*;
import com.manliao.backend.billing.*;
import com.manliao.backend.identity.*;
import com.manliao.backend.common.ApiError;
import static org.assertj.core.api.Assertions.*;
@Import(TestcontainersConfiguration.class)
@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT,properties={"app.auth.legacy-registration-enabled=true","app.auth.jwt-secret=isolated-wallet-tests-secret-at-least-thirty-two-bytes","app.accounts.worker-enabled=false","app.realtime.worker-enabled=false","app.media.derivatives-worker-enabled=false","app.media.jobs-worker-enabled=false","app.media.draft-worker-enabled=false","app.environment=test","app.billing.dev-recharge-enabled=true"})
class GiftSafetyIntegrationTests {
 @Value("${local.server.port}") int port;
 @Autowired com.manliao.backend.admin.AdminService admins;
 @Autowired JdbcTemplate db;@Autowired ObjectMapper json;@Autowired LedgerService ledger;@Autowired WalletService wallet;@Autowired AccountLifecycleService accounts;@Autowired TransactionTemplate tx;
 @Autowired com.manliao.backend.gifts.GiftSafetyService safety;
 final HttpClient http=HttpClient.newHttpClient();int sequence;
 record Reply(int status,JsonNode body){String text(String key){return body.get(key).asString();}}
 record User(String id,String token,String session){}
 @BeforeEach void clean(){db.execute("TRUNCATE admin_users,users,conversations,auth_rate_windows RESTART IDENTITY CASCADE");sequence=1;}
 Reply call(String method,String path,Object body,User user)throws Exception{
  var b=HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+path)).timeout(java.time.Duration.ofSeconds(15));if(user!=null)b.header("Authorization","Bearer "+user.token());if(body!=null)b.header("Content-Type","application/json");
  var r=http.send(b.method(method,body==null?HttpRequest.BodyPublishers.noBody():HttpRequest.BodyPublishers.ofString(json.writeValueAsString(body))).build(),HttpResponse.BodyHandlers.ofString());
  return new Reply(r.statusCode(),r.body().isBlank()?null:json.readTree(r.body()));
 }
 User user()throws Exception{
  var r=call("POST","/auth/register",Map.of("phone","1398100"+String.format("%04d",sequence++),"nickname","账本测试","password","Wallet-test-password"),null);
  assertThat(r.status()).isEqualTo(200);return new User(r.text("user_id"),r.text("access_token"),r.text("session_id"));
 }
 User owner()throws Exception{admins.bootstrap(new com.manliao.backend.admin.AdminDtos.Create("risk_owner","Owner-test-password-123","owner","owner"));var r=call("POST","/admin/auth/login",Map.of("username","risk_owner","password","Owner-test-password-123"),null);return new User("admin",r.text("access_token"),null);}
 Reply get(User a)throws Exception{return call("GET","/live/gift-safety/me",null,a);}
 Reply update(User a,Object input)throws Exception{return call("PATCH","/live/gift-safety/me",input,a);}
 String event(User a){return tx.execute(s->{wallet.lock(new AuthDtos.Principal(a.id(),a.session()));return safety.record(a.id(),null,"single_limit_exceeded","high","open",10001,Map.of("single_limit_coins",10000));});}
 @Test void defaultsArePrivateAndAgeCannotBeSelfAssigned()throws Exception{var a=user();var r=get(a);assertThat(r.status()).isEqualTo(200);assertThat(r.body().get("effective_single_limit_coins").asLong()).isEqualTo(10000);assertThat(r.body().get("effective_daily_limit_coins").asLong()).isEqualTo(20000);assertThat(r.body().get("ranking_consent").asBoolean()).isFalse();assertThat(update(a,Map.of("age_status","adult")).text("age_status")).isEqualTo("unverified");assertThat(call("GET","/live/gift-safety/me",null,null).status()).isEqualTo(401);}
 @Test void personalLimitsCanBeLoweredAndResetButNotExceedPlatform()throws Exception{var a=user();var r=update(a,Map.of("single_limit_coins",50,"daily_limit_coins",100));assertThat(r.body().get("today_remaining_coins").asLong()).isEqualTo(100);assertThat(update(a,Map.of("single_limit_coins",10001)).status()).isEqualTo(422);assertThat(update(a,Map.of("daily_limit_coins",20001)).status()).isEqualTo(422);var nil=new HashMap<String,Object>();nil.put("single_limit_coins",null);nil.put("daily_limit_coins",null);assertThat(update(a,nil).body().get("effective_daily_limit_coins").asLong()).isEqualTo(20000);}
 @Test void reminderRankingAndAcknowledgementPreserveFirstTimestamp()throws Exception{var a=user();var r=update(a,Map.of("reminder_enabled",false,"reminder_threshold_coins",25,"ranking_consent",true,"acknowledge_settings_offer",true));String at=r.text("first_gift_settings_offered_at");assertThat(r.body().get("ranking_consent").asBoolean()).isTrue();assertThat(update(a,Map.of("acknowledge_settings_offer",true)).text("first_gift_settings_offered_at")).isEqualTo(at);var b=user();assertThat(get(b).body().get("ranking_consent").asBoolean()).isFalse();}
 @Test void malformedLimitsAndBooleansFailWithoutPartialUpdate()throws Exception{var a=user();for(var input:List.of(Map.of("single_limit_coins",0),Map.of("daily_limit_coins",1.5),Map.of("ranking_consent","yes"),Map.of("reminder_threshold_coins",100001),Map.of("acknowledge_settings_offer","yes"))){assertThat(update(a,input).status()).isEqualTo(422);}assertThat(get(a).body().get("single_limit_coins").isNull()).isTrue();}
 @Test void administratorAgeChangeIsAuditedAndDoesNotImplyHostIdentity()throws Exception{var a=user();var admin=owner();var r=call("PATCH","/admin/gift-risk/users/"+a.id()+"/age-status",Map.of("age_status","adult","reason","合成年龄测试"),admin);assertThat(r.status()).isEqualTo(200);assertThat(get(a).text("age_status")).isEqualTo("adult");assertThat(db.queryForObject("SELECT count(*) FROM gift_risk_events WHERE status='confirmed'",Integer.class)).isEqualTo(1);assertThat(db.queryForObject("SELECT count(*) FROM live_host_qualifications",Integer.class)).isZero();assertThat(call("PATCH","/admin/gift-risk/users/"+a.id()+"/age-status",Map.of("age_status","adult","reason","合成测试"),a).status()).isIn(401,403);}
 @Test void riskResolutionOnlyOnceWithConcurrentRequests()throws Exception{var a=user();var admin=owner();String id=event(a);try(var pool=Executors.newVirtualThreadPerTaskExecutor()){var x=pool.submit(()->call("POST","/admin/gift-risk/events/"+id+"/resolve",Map.of("decision","reviewed","resolution","人工检查"),admin));var y=pool.submit(()->call("POST","/admin/gift-risk/events/"+id+"/resolve",Map.of("decision","dismissed","resolution","人工检查"),admin));assertThat(List.of(x.get().status(),y.get().status())).containsExactlyInAnyOrder(200,409);}assertThat(db.queryForObject("SELECT count(*) FROM admin_operation_logs WHERE action='gift_risk.resolve'",Integer.class)).isEqualTo(1);}
 @Test void adminListFiltersAndLimits()throws Exception{var a=user();var admin=owner();event(a);assertThat(call("GET","/admin/gift-risk/events?user_id="+a.id()+"&status=open",null,admin).body().size()).isEqualTo(1);assertThat(call("GET","/admin/gift-risk/events?event_type=missing",null,admin).body().size()).isZero();assertThat(call("GET","/admin/gift-risk/events?limit=501",null,admin).status()).isEqualTo(422);assertThat(call("POST","/admin/gift-risk/events/missing/resolve",Map.of("decision","reviewed","resolution","人工检查"),admin).status()).isEqualTo(404);}
 @Test void auditFailureRollsBackAgeChangeAndRiskRecord()throws Exception{var a=user();var admin=owner();db.execute("ALTER TABLE admin_operation_logs ADD CONSTRAINT risk_audit_failure CHECK(action<>'gift_risk.age_status.update') NOT VALID");try{assertThat(call("PATCH","/admin/gift-risk/users/"+a.id()+"/age-status",Map.of("age_status","adult","reason","合成测试"),admin).status()).isEqualTo(500);}finally{db.execute("ALTER TABLE admin_operation_logs DROP CONSTRAINT risk_audit_failure");}assertThat(get(a).text("age_status")).isEqualTo("unverified");assertThat(db.queryForObject("SELECT count(*) FROM gift_risk_events",Integer.class)).isZero();}
 @Test void erasureDeletesSettingsAndUnlinkedRiskData()throws Exception{var a=user();get(a);event(a);db.update("UPDATE users SET status='deactivation_pending',deactivation_due_at=now()-interval '1 day' WHERE id=?",a.id());assertThat(accounts.eraseDue(a.id())).isTrue();assertThat(db.queryForObject("SELECT count(*) FROM gift_safety_settings",Integer.class)).isZero();assertThat(db.queryForObject("SELECT count(*) FROM gift_risk_events",Integer.class)).isZero();assertThat(get(a).status()).isIn(401,403);}
 @Test void auditorCanReadButNotModifyRiskState()throws Exception{var a=user();event(a);var admin=owner();call("POST","/admin/admin-users",Map.of("username","risk_auditor","password","Auditor-test-password-123","display_name","audit","role","auditor"),admin);var login=call("POST","/admin/auth/login",Map.of("username","risk_auditor","password","Auditor-test-password-123"),null);var auditor=new User("admin",login.text("access_token"),null);assertThat(call("GET","/admin/gift-risk/events",null,auditor).status()).isEqualTo(200);assertThat(call("PATCH","/admin/gift-risk/users/"+a.id()+"/age-status",Map.of("age_status","adult","reason","合成测试"),auditor).status()).isEqualTo(403);}
 @Test void todaySpendUsesCommittedGiftChargesAndExcludesReversals()throws Exception{var a=user();call("POST","/wallet/recharge/dev",Map.of("amount",100,"client_request_id","safety-fixture-credit"),a);var charge=ledger.post(new LedgerService.Posting("safety-gift-charge","gift_charge",30,List.of(LedgerService.spendable(a.id(),-30,"sender_charge"),LedgerService.platform("platform_gift_revenue",30,"fixture_income")),a.id(),"live_gift","fixture",Map.of(),null,"gift_charge","fixture"));assertThat(get(a).body().get("today_spent_coins").asLong()).isEqualTo(30);assertThat(update(a,Map.of("daily_limit_coins",20)).body().get("today_remaining_coins").asLong()).isZero();ledger.post(new LedgerService.Posting("safety-gift-refund","gift_refund",30,List.of(LedgerService.spendable(a.id(),30,"sender_refund"),LedgerService.platform("platform_gift_revenue",-30,"fixture_reversal")),null,"live_gift","fixture",Map.of(),charge.id(),"refund","fixture"));assertThat(get(a).body().get("today_spent_coins").asLong()).isZero();assertThat(get(a).body().get("today_remaining_coins").asLong()).isEqualTo(20);}
}