package com.manliao.backend;
import java.net.*;
import java.net.http.*;
import java.util.*;
import java.util.concurrent.*;
import java.io.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.*;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;
import tools.jackson.databind.*;
import com.manliao.backend.admin.*;
import static org.assertj.core.api.Assertions.*;
@Import(TestcontainersConfiguration.class)
@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT,properties={"app.auth.jwt-secret=isolated-gifts-tests-secret-at-least-thirty-two-bytes","app.accounts.worker-enabled=false","app.realtime.worker-enabled=false","app.media.derivatives-worker-enabled=false","app.media.jobs-worker-enabled=false","app.media.draft-worker-enabled=false"})
class GiftCatalogIntegrationTests {
 @Value("${local.server.port}") int port;@Autowired AdminService admins;@Autowired JdbcTemplate db;@Autowired ObjectMapper json;
 final HttpClient http=HttpClient.newHttpClient();String owner;
 record Reply(int status,JsonNode body){String text(String key){return body.get(key).asString();}}
 @BeforeEach void clean()throws Exception{db.execute("TRUNCATE admin_users,auth_rate_windows,live_gift_assets RESTART IDENTITY CASCADE");db.update("DELETE FROM live_gift_catalog_items WHERE id NOT IN ('gift_catalog_rose','gift_catalog_candy','gift_catalog_coffee','gift_catalog_heart','gift_catalog_star_bottle','gift_catalog_meteor','gift_catalog_bouquet','gift_catalog_diamond','gift_catalog_firework','gift_catalog_rocket','gift_catalog_crown','gift_catalog_galaxy_promise')");db.update("UPDATE live_gift_catalog_items SET status='active',icon_url=NULL,animation_url=NULL,renderer_type='static',animation_checksum=NULL,animation_file_size=NULL,resource_version=1");admins.bootstrap(new AdminDtos.Create("gift_owner","Owner-test-password-123","owner","owner"));owner=login("gift_owner","Owner-test-password-123");}
 String login(String name,String pass)throws Exception{return call("POST","/admin/auth/login",Map.of("username",name,"password",pass),null).text("access_token");}
 Reply call(String method,String path,Object body,String token)throws Exception{var b=HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+path)).timeout(java.time.Duration.ofSeconds(15));if(token!=null)b.header("Authorization","Bearer "+token);if(body!=null)b.header("Content-Type","application/json");var r=http.send(b.method(method,body==null?HttpRequest.BodyPublishers.noBody():HttpRequest.BodyPublishers.ofString(json.writeValueAsString(body))).build(),HttpResponse.BodyHandlers.ofString());return new Reply(r.statusCode(),r.body().isBlank()?null:json.readTree(r.body()));}
 Reply create(String code)throws Exception{return call("POST","/admin/live-gifts",Map.of("code",code,"name","礼物","price_coins",25),owner);}
 Reply upload(String gift,String kind,byte[] bytes,String token)throws Exception{
  var out=new ByteArrayOutputStream();out.write("--gift-boundary\r\nContent-Disposition: form-data; name=\"file\"; filename=\"untrusted-name.bin\"\r\nContent-Type: application/octet-stream\r\n\r\n".getBytes(java.nio.charset.StandardCharsets.UTF_8));out.write(bytes);out.write("\r\n--gift-boundary--\r\n".getBytes());var b=HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+"/admin/live-gifts/"+gift+"/assets/"+kind)).header("Content-Type","multipart/form-data; boundary=gift-boundary");if(token!=null)b.header("Authorization","Bearer "+token);var r=http.send(b.POST(HttpRequest.BodyPublishers.ofByteArray(out.toByteArray())).build(),HttpResponse.BodyHandlers.ofString());return new Reply(r.statusCode(),json.readTree(r.body()));
 }
 byte[] png()throws Exception{var out=new ByteArrayOutputStream();javax.imageio.ImageIO.write(new java.awt.image.BufferedImage(2,2,java.awt.image.BufferedImage.TYPE_INT_ARGB),"png",out);return out.toByteArray();}
 byte[] lottie(){return "{\"v\":\"5.7.4\",\"fr\":30,\"ip\":0,\"op\":30,\"layers\":[]}".getBytes();}
 @Test void defaultsArePublicSortedAndHideAdminFields()throws Exception{var r=call("GET","/live/gifts",null,null);assertThat(r.status()).isEqualTo(200);assertThat(r.body().size()).isEqualTo(12);assertThat(r.body().get(0).get("code").asString()).isEqualTo("rose");assertThat(r.body().get(11).get("price_coins").asLong()).isEqualTo(5200);assertThat(r.body().get(0).has("id")).isFalse();assertThat(r.body().get(0).has("status")).isFalse();}
 @Test void createDefaultsAndUniqueCode()throws Exception{var r=create("new_gift");assertThat(r.status()).isEqualTo(200);assertThat(r.text("renderer_type")).isEqualTo("static");assertThat(r.body().get("resource_version").asInt()).isEqualTo(1);assertThat(create("new_gift").status()).isEqualTo(409);assertThat(db.queryForObject("SELECT count(*) FROM admin_operation_logs WHERE action='live_gift_catalog.create'",Integer.class)).isEqualTo(1);}
 @Test void inactiveGiftIsHiddenButAdminCanReactivate()throws Exception{String id=create("hidden_gift").text("id");assertThat(call("PATCH","/admin/live-gifts/"+id,Map.of("status","inactive"),owner).status()).isEqualTo(200);assertThat(call("GET","/live/gifts",null,null).body().size()).isEqualTo(12);assertThat(call("GET","/admin/live-gifts",null,owner).body().size()).isEqualTo(13);var r=call("PATCH","/admin/live-gifts/"+id,Map.of("status","active"),owner);assertThat(r.body().get("resource_version").asInt()).isEqualTo(3);assertThat(call("GET","/live/gifts",null,null).body().size()).isEqualTo(13);}
 @Test void validationRejectsNullsFractionsBoundsAndExecutableUrls()throws Exception{for(var v:List.of(Map.of("price_coins",0),Map.of("price_coins",1.5),Map.of("price_coins",1000001),Map.of("animation_duration_ms",299),Map.of("status","deleted"),Map.of("icon_url","javascript:alert(1)"),Map.of("renderer_type","unknown"),Map.of("name","   "))){assertThat(call("PATCH","/admin/live-gifts/gift_catalog_rose",v,owner).status()).isEqualTo(422);}var nil=new HashMap<String,Object>();nil.put("price_coins",null);assertThat(call("PATCH","/admin/live-gifts/gift_catalog_rose",nil,owner).status()).isEqualTo(422);assertThat(call("POST","/admin/live-gifts",Map.of("code","../bad","name","x","price_coins",1),owner).status()).isEqualTo(422);}
 @Test void optionalFieldsCanBeClearedAndMissingGiftReturns404()throws Exception{String id=create("optional_gift").text("id");assertThat(call("PATCH","/admin/live-gifts/"+id,Map.of("icon_url","https://example.com/icon.png","min_client_version","1.0"),owner).status()).isEqualTo(200);var nil=new HashMap<String,Object>();nil.put("icon_url",null);nil.put("min_client_version",null);var r=call("PATCH","/admin/live-gifts/"+id,nil,owner);assertThat(r.body().get("icon_url").isNull()).isTrue();assertThat(call("PATCH","/admin/live-gifts/missing",Map.of(),owner).status()).isEqualTo(404);}
 @Test void auditorReadsOnlyAndOperatorWrites()throws Exception{for(String role:List.of("auditor","operator")){assertThat(call("POST","/admin/admin-users",Map.of("username","gift_"+role,"password","Role-test-password-123","display_name",role,"role",role),owner).status()).isEqualTo(200);String token=login("gift_"+role,"Role-test-password-123");assertThat(call("GET","/admin/live-gifts",null,token).status()).isEqualTo(200);assertThat(call("PATCH","/admin/live-gifts/gift_catalog_rose",Map.of("status","inactive"),token).status()).isEqualTo(role.equals("operator")?200:403);assertThat(upload("gift_catalog_rose","icon",png(),token).status()).isEqualTo(role.equals("operator")?200:403);}assertThat(call("GET","/admin/live-gifts",null,null).status()).isEqualTo(401);}
 @Test void iconUploadIsPublicByteExactAndVersioned()throws Exception{byte[] bytes=png();var r=upload("gift_catalog_rose","icon",bytes,owner);assertThat(r.status()).isEqualTo(200);assertThat(r.body().get("resource_version").asInt()).isEqualTo(2);String path=URI.create(r.text("icon_url")).getPath();var fetched=http.send(HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+path)).build(),HttpResponse.BodyHandlers.ofByteArray());assertThat(fetched.statusCode()).isEqualTo(200);assertThat(fetched.body()).isEqualTo(bytes);assertThat(fetched.headers().firstValue("Content-Type")).contains("image/png");assertThat(fetched.headers().firstValue("X-Content-Type-Options")).contains("nosniff");}
 @Test void lottieUploadHasChecksumAndChangingExternalUrlClearsIt()throws Exception{var r=upload("gift_catalog_rose","animation",lottie(),owner);assertThat(r.status()).isEqualTo(200);assertThat(r.text("renderer_type")).isEqualTo("lottie");assertThat(r.text("animation_checksum")).hasSize(64);assertThat(r.body().get("animation_file_size").asInt()).isEqualTo(lottie().length);var changed=call("PATCH","/admin/live-gifts/gift_catalog_rose",Map.of("animation_url","https://example.com/updated.json"),owner);assertThat(changed.body().get("animation_checksum").isNull()).isTrue();assertThat(changed.body().get("animation_file_size").isNull()).isTrue();}
 @Test void malformedAssetsAreRejectedWithoutRowsOrVersionChanges()throws Exception{for(byte[] data:List.of(new byte[0],new byte[]{1,2,3},"<script>test</script>".getBytes()))assertThat(upload("gift_catalog_rose","icon",data,owner).status()).isEqualTo(422);for(String data:List.of("{}","[]","{\"v\":\"1\",\"fr\":30,\"ip\":2,\"op\":1,\"layers\":[]}","{\"v\":\"1\",\"fr\":\"oops\",\"ip\":0,\"op\":1,\"layers\":[]}"))assertThat(upload("gift_catalog_rose","animation",data.getBytes(),owner).status()).isEqualTo(422);assertThat(upload("gift_catalog_rose","animation",new byte[]{(byte)0xff},owner).status()).isEqualTo(422);assertThat(db.queryForObject("SELECT count(*) FROM live_gift_assets",Integer.class)).isZero();assertThat(db.queryForObject("SELECT resource_version FROM live_gift_catalog_items WHERE code='rose'",Integer.class)).isEqualTo(1);}
 @Test void oversizedAndUnsupportedAssetTypesFail()throws Exception{assertThat(upload("gift_catalog_rose","animation",new byte[2*1024*1024+1],owner).status()).isEqualTo(413);assertThat(upload("gift_catalog_rose","icon",new byte[5*1024*1024+1],owner).status()).isEqualTo(413);assertThat(upload("gift_catalog_rose","video",png(),owner).status()).isEqualTo(422);assertThat(upload("missing","icon",png(),owner).status()).isEqualTo(404);assertThat(call("GET","/gift-assets/unknown",null,null).status()).isEqualTo(404);}
 @Test void assetAndCatalogUpdateRollbackTogether()throws Exception{db.execute("ALTER TABLE admin_operation_logs ADD CONSTRAINT gift_audit_failure CHECK(action<>'live_gift_catalog.asset_upload') NOT VALID");try{assertThat(upload("gift_catalog_rose","icon",png(),owner).status()).isEqualTo(500);}finally{db.execute("ALTER TABLE admin_operation_logs DROP CONSTRAINT gift_audit_failure");}assertThat(db.queryForObject("SELECT count(*) FROM live_gift_assets",Integer.class)).isZero();assertThat(db.queryForObject("SELECT resource_version FROM live_gift_catalog_items WHERE code='rose'",Integer.class)).isEqualTo(1);}
 @Test void concurrentUploadsIncrementWithoutLostUpdates()throws Exception{byte[] bytes=png();try(var pool=Executors.newVirtualThreadPerTaskExecutor()){var jobs=new ArrayList<Future<Reply>>();for(int i=0;i<4;i++)jobs.add(pool.submit(()->upload("gift_catalog_rose","animation",lottie(),owner)));for(var job:jobs)assertThat(job.get().status()).isEqualTo(200);}assertThat(db.queryForObject("SELECT resource_version FROM live_gift_catalog_items WHERE code='rose'",Integer.class)).isEqualTo(5);assertThat(db.queryForObject("SELECT count(*) FROM live_gift_assets",Integer.class)).isEqualTo(4);}
}
