package com.manliao.backend;
import java.net.*;
import java.net.http.*;
import java.util.*;
import java.util.concurrent.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.*;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.support.TransactionTemplate;
import tools.jackson.databind.*;
import com.manliao.backend.billing.*;
import com.manliao.backend.identity.*;
import com.manliao.backend.common.ApiError;
import static org.assertj.core.api.Assertions.*;
@Import(TestcontainersConfiguration.class)
@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT,properties={"app.auth.legacy-registration-enabled=true","app.auth.jwt-secret=isolated-host-tests-secret-at-least-thirty-two-bytes","app.accounts.worker-enabled=false","app.realtime.worker-enabled=false","app.media.derivatives-worker-enabled=false","app.media.jobs-worker-enabled=false","app.media.draft-worker-enabled=false","app.environment=test","app.billing.dev-recharge-enabled=true"})
class HostVerificationIntegrationTests {
 @Value("${local.server.port}") int port;
 @Autowired com.manliao.backend.admin.AdminService admins;
 @Autowired JdbcTemplate db;@Autowired ObjectMapper json;@Autowired LedgerService ledger;@Autowired WalletService wallet;@Autowired AccountLifecycleService accounts;@Autowired TransactionTemplate tx;
 @Autowired com.manliao.backend.live.HostVerificationService host;
 final HttpClient http=HttpClient.newHttpClient();int sequence;
 record Reply(int status,JsonNode body){String text(String key){return body.get(key).asString();}}
 record User(String id,String token,String session){}
 @BeforeEach void clean(){db.execute("TRUNCATE admin_users,users,conversations,auth_rate_windows RESTART IDENTITY CASCADE");sequence=1;}
 Reply call(String method,String path,Object body,User user)throws Exception{
  var b=HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+path)).timeout(java.time.Duration.ofSeconds(15));if(user!=null)b.header("Authorization","Bearer "+user.token());if(body!=null)b.header("Content-Type","application/json");
  var r=http.send(b.method(method,body==null?HttpRequest.BodyPublishers.noBody():HttpRequest.BodyPublishers.ofString(json.writeValueAsString(body))).build(),HttpResponse.BodyHandlers.ofString());
  return new Reply(r.statusCode(),r.body().isBlank()?null:json.readTree(r.body()));
 }
 User user()throws Exception{
  var r=call("POST","/auth/register",Map.of("phone","1398100"+String.format("%04d",sequence++),"nickname","账本测试","password","Wallet-test-password"),null);
  assertThat(r.status()).isEqualTo(200);return new User(r.text("user_id"),r.text("access_token"),r.text("session_id"));
 }
 User owner()throws Exception{admins.bootstrap(new com.manliao.backend.admin.AdminDtos.Create("host_owner","Owner-test-password-123","owner","owner"));var r=call("POST","/admin/auth/login",Map.of("username","host_owner","password","Owner-test-password-123"),null);return new User("admin",r.text("access_token"),null);}
 Map<String,Object> payload(java.time.LocalDate date){return new LinkedHashMap<>(Map.of("legal_name","测试用户","id_number","TESTONLY12345678","date_of_birth",date.toString(),"guardian_consent",false,"agreement_accepted",true));}
 Reply submit(User user)throws Exception{return call("POST","/live/host-verification/applications",payload(java.time.LocalDate.of(1990,1,1)),user);}
 String app(Reply r){return r.body().get("applications").get(0).get("id").asString();}
 Reply review(User owner,String app,String decision,boolean gifts)throws Exception{return call("POST","/admin/host-verification/applications/"+app+"/resolve",Map.of("decision",decision,"allow_gifts",gifts,"reason","审核记录"),owner);}
 @Test void initialQualificationIsUnverifiedAndPrivate()throws Exception{var a=user();var r=call("GET","/live/host-verification/me",null,a);assertThat(r.status()).isEqualTo(200);assertThat(r.body().get("qualification").get("agreement_version").asString()).isEqualTo("2026-07");assertThat(r.body().get("qualification").get("identity_status").asString()).isEqualTo("unverified");assertThat(r.body().get("qualification").get("can_receive_gifts").asBoolean()).isFalse();assertThat(call("GET","/live/host-verification/me",null,null).status()).isEqualTo(401);}
 @Test void birthAgeConsentAndAgreementRules()throws Exception{var a=user();var now=java.time.LocalDate.now(java.time.ZoneOffset.UTC);assertThat(call("POST","/live/host-verification/applications",payload(now.minusYears(15)),a).status()).isEqualTo(403);assertThat(call("POST","/live/host-verification/applications",payload(now.plusDays(1)),a).status()).isEqualTo(400);assertThat(call("POST","/live/host-verification/applications",payload(now.minusYears(17)),a).status()).isEqualTo(400);var p=payload(now.minusYears(17));p.put("guardian_consent",true);p.put("agreement_accepted",false);assertThat(call("POST","/live/host-verification/applications",p,a).status()).isEqualTo(400);p.put("agreement_accepted",true);assertThat(call("POST","/live/host-verification/applications",p,a).status()).isEqualTo(200);}
 @Test void masksAndHashesIdentityWithoutReturningOrAuditingRawValues()throws Exception{var a=user();var r=submit(a);assertThat(r.status()).isEqualTo(200);assertThat(r.body().toString()).doesNotContain("TESTONLY12345678","id_number_hash","测试用户");assertThat(r.body().get("applications").get(0).get("legal_name_masked").asString()).isEqualTo("测***");assertThat(db.queryForObject("SELECT id_number_hash FROM live_host_verification_applications",String.class)).hasSize(64);assertThat(submit(a).status()).isEqualTo(409);var b=user();assertThat(call("GET","/live/host-verification/me",null,b).body().get("applications").size()).isZero();}
 @Test void concurrentSubmissionAllowsOnlyOnePending()throws Exception{var a=user();try(var pool=Executors.newVirtualThreadPerTaskExecutor()){var jobs=new ArrayList<Future<Reply>>();for(int i=0;i<6;i++)jobs.add(pool.submit(()->submit(a)));var codes=new ArrayList<Integer>();for(var j:jobs)codes.add(j.get().status());assertThat(codes.stream().filter(c->c==200).count()).isEqualTo(1);assertThat(codes.stream().filter(c->c==409).count()).isEqualTo(5);}assertThat(db.queryForObject("SELECT count(*) FROM live_host_verification_applications",Integer.class)).isEqualTo(1);}
 @Test void approvalEnablesStartAndExplicitGiftPermissionAndNotifiesOnce()throws Exception{var a=user();var admin=owner();assertThatThrownBy(()->tx.executeWithoutResult(s->host.assertCanStart(a.id()))).isInstanceOf(ApiError.class);String id=app(submit(a));var r=review(admin,id,"approved",true);assertThat(r.status()).isEqualTo(200);assertThat(r.body().get("qualification").get("can_receive_gifts").asBoolean()).isTrue();tx.executeWithoutResult(s->{host.assertCanStart(a.id());host.assertCanReceive(a.id());});assertThat(review(admin,id,"approved",true).status()).isEqualTo(409);assertThat(db.queryForObject("SELECT count(*) FROM notification_events WHERE event_type='host_verification_reviewed'",Integer.class)).isEqualTo(1);assertThat(db.queryForObject("SELECT count(*) FROM admin_operation_logs WHERE action='live_host_verification.resolve'",Integer.class)).isEqualTo(1);}
 @Test void rejectionRequiresReasonAndAllowsNewApplication()throws Exception{var a=user();var admin=owner();String id=app(submit(a));assertThat(call("POST","/admin/host-verification/applications/"+id+"/resolve",Map.of("decision","rejected","reason","   "),admin).status()).isEqualTo(400);var rejected=review(admin,id,"rejected",false);assertThat(rejected.body().get("qualification").get("identity_status").asString()).isEqualTo("rejected");assertThat(submit(a).status()).isEqualTo(200);assertThat(review(admin,id,"approved",true).status()).isEqualTo(409);}
 @Test void suspensionBlocksReapplicationAndRestoreDoesNotRestoreGifts()throws Exception{var a=user();var admin=owner();review(admin,app(submit(a)),"approved",true);assertThat(call("POST","/admin/host-verification/qualifications/"+a.id()+"/suspend",Map.of("reason","暂停测试"),admin).status()).isEqualTo(200);assertThat(submit(a).status()).isEqualTo(409);assertThatThrownBy(()->tx.executeWithoutResult(s->host.assertCanStart(a.id()))).isInstanceOf(ApiError.class);assertThat(call("POST","/admin/host-verification/qualifications/"+a.id()+"/restore",null,admin).status()).isEqualTo(200);tx.executeWithoutResult(s->host.assertCanStart(a.id()));assertThatThrownBy(()->tx.executeWithoutResult(s->host.assertCanReceive(a.id()))).isInstanceOf(ApiError.class);}
 @Test void suspendedPendingApplicationCanBeReviewedWithoutBypass()throws Exception{var a=user();var admin=owner();String id=app(submit(a));call("POST","/admin/host-verification/qualifications/"+a.id()+"/suspend",Map.of("reason","暂停测试"),admin);var r=review(admin,id,"approved",true);assertThat(r.status()).isEqualTo(200);assertThat(r.body().get("qualification").get("agreement_version").asString()).isEqualTo("2026-07");assertThat(r.body().get("qualification").get("identity_status").asString()).isEqualTo("verified");assertThat(r.body().get("qualification").get("host_permission_status").asString()).isEqualTo("suspended");assertThat(r.body().get("qualification").get("can_receive_gifts").asBoolean()).isFalse();assertThatThrownBy(()->tx.executeWithoutResult(s->host.assertCanStart(a.id()))).isInstanceOf(ApiError.class);}
 @Test void expirationRestoresOnlyVerifiedStartPermission()throws Exception{var a=user();var admin=owner();review(admin,app(submit(a)),"approved",true);call("POST","/admin/host-verification/qualifications/"+a.id()+"/suspend",Map.of("reason","到期测试","restriction_until",java.time.Instant.now().plusSeconds(60).toString()),admin);db.update("UPDATE live_host_qualifications SET restriction_until=now()-interval '1 second' WHERE user_id=?",a.id());tx.executeWithoutResult(s->host.assertCanStart(a.id()));assertThat(db.queryForObject("SELECT host_permission_status FROM live_host_qualifications WHERE user_id=?",String.class,a.id())).isEqualTo("enabled");assertThatThrownBy(()->tx.executeWithoutResult(s->host.assertCanReceive(a.id()))).isInstanceOf(ApiError.class);}
 @Test void auditFailureRollsBackApprovalAndNotification()throws Exception{var a=user();var admin=owner();String id=app(submit(a));db.execute("ALTER TABLE admin_operation_logs ADD CONSTRAINT host_audit_failure CHECK(action<>'live_host_verification.resolve') NOT VALID");try{assertThat(review(admin,id,"approved",true).status()).isEqualTo(500);}finally{db.execute("ALTER TABLE admin_operation_logs DROP CONSTRAINT host_audit_failure");}assertThat(db.queryForObject("SELECT status FROM live_host_verification_applications WHERE id=?",String.class,id)).isEqualTo("pending_review");assertThat(db.queryForObject("SELECT count(*) FROM notification_events WHERE event_type='host_verification_reviewed'",Integer.class)).isZero();assertThat(review(admin,id,"approved",true).status()).isEqualTo(200);}
 @Test void adminFiltersAndUserCannotReview()throws Exception{var a=user();String id=app(submit(a));assertThat(review(a,id,"approved",true).status()).isIn(401,403);var admin=owner();assertThat(call("GET","/admin/host-verification/applications?status=pending_review&user_id="+a.id(),null,admin).body().size()).isEqualTo(1);assertThat(call("GET","/admin/host-verification/applications?status=rejected",null,admin).body().size()).isZero();assertThat(call("GET","/admin/host-verification/applications",null,admin).body().toString()).doesNotContain("id_number_hash");db.update("UPDATE admin_users SET status='disabled'");assertThat(review(admin,id,"approved",true).status()).isIn(401,403);}
 @Test void reapplicationRevokesPreviousGiftPermissionUntilReviewed()throws Exception{var a=user();var admin=owner();review(admin,app(submit(a)),"approved",true);var pending=submit(a);assertThat(pending.status()).isEqualTo(200);assertThat(pending.body().get("qualification").get("can_receive_gifts").asBoolean()).isFalse();assertThatThrownBy(()->tx.executeWithoutResult(s->host.assertCanReceive(a.id()))).isInstanceOf(ApiError.class);}
 @Test void unverifiedCannotRestoreAndInvalidInputFails()throws Exception{var a=user();var admin=owner();assertThat(call("POST","/admin/host-verification/qualifications/"+a.id()+"/restore",null,admin).status()).isEqualTo(409);assertThat(call("POST","/admin/host-verification/qualifications/"+a.id()+"/suspend",Map.of("reason","   "),admin).status()).isEqualTo(422);var p=payload(java.time.LocalDate.of(1990,1,1));p.put("legal_name","   ");assertThat(call("POST","/live/host-verification/applications",p,a).status()).isEqualTo(422);}
 @Test void erasureDeletesMaskedIdentityAndQualificationAndPreventsRecreation()throws Exception{var a=user();submit(a);db.update("UPDATE users SET status='deactivation_pending',deactivation_due_at=now()-interval '1 day' WHERE id=?",a.id());assertThat(accounts.eraseDue(a.id())).isTrue();assertThat(db.queryForObject("SELECT count(*) FROM live_host_verification_applications WHERE user_id=?",Integer.class,a.id())).isZero();assertThat(db.queryForObject("SELECT count(*) FROM live_host_qualifications WHERE user_id=?",Integer.class,a.id())).isZero();assertThat(call("GET","/live/host-verification/me",null,a).status()).isIn(401,403);}
 @Test void expiredSuspensionDoesNotPermanentlyBlockRejectedApplicant()throws Exception{var a=user();var admin=owner();String id=app(submit(a));call("POST","/admin/host-verification/qualifications/"+a.id()+"/suspend",Map.of("reason","暂停测试"),admin);review(admin,id,"rejected",false);assertThat(submit(a).status()).isEqualTo(409);db.update("UPDATE live_host_qualifications SET restriction_until=now()-interval '1 second' WHERE user_id=?",a.id());assertThat(submit(a).status()).isEqualTo(200);assertThat(db.queryForObject("SELECT can_receive_gifts FROM live_host_qualifications WHERE user_id=?",Boolean.class,a.id())).isFalse();}
 @Test void unsuspendingRejectedIdentityDoesNotGrantLivePermission()throws Exception{var a=user();var admin=owner();String id=app(submit(a));call("POST","/admin/host-verification/qualifications/"+a.id()+"/suspend",Map.of("reason","暂停测试"),admin);review(admin,id,"rejected",false);var r=call("POST","/admin/host-verification/qualifications/"+a.id()+"/restore",null,admin);assertThat(r.status()).isEqualTo(200);assertThat(r.body().get("qualification").get("host_permission_status").asString()).isEqualTo("not_applied");assertThatThrownBy(()->tx.executeWithoutResult(s->host.assertCanStart(a.id()))).isInstanceOf(ApiError.class);assertThat(submit(a).status()).isEqualTo(200);}
}