package com.manliao.backend;
import java.net.*;
import java.net.http.*;
import java.util.*;
import java.util.concurrent.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.*;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.support.TransactionTemplate;
import tools.jackson.databind.*;
import com.manliao.backend.billing.*;
import com.manliao.backend.identity.*;
import com.manliao.backend.common.ApiError;
import static org.assertj.core.api.Assertions.*;
@Import(TestcontainersConfiguration.class)
@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT,properties={"app.auth.legacy-registration-enabled=true","app.auth.jwt-secret=isolated-live-tests-secret-at-least-thirty-two-bytes","app.accounts.worker-enabled=false","app.realtime.worker-enabled=false","app.media.derivatives-worker-enabled=false","app.media.jobs-worker-enabled=false","app.media.draft-worker-enabled=false","app.environment=test","app.live.provider=mock","app.live.mock-enabled=true","app.billing.dev-recharge-enabled=true"})
class LiveGiftIntegrationTests {
 @Value("${local.server.port}") int port;
 @Autowired com.manliao.backend.admin.AdminService admins;
 @Autowired JdbcTemplate db;@Autowired ObjectMapper json;@Autowired LedgerService ledger;@Autowired WalletService wallet;@Autowired AccountLifecycleService accounts;@Autowired TransactionTemplate tx;
 @Autowired com.manliao.backend.live.HostVerificationService host;
 @Autowired com.manliao.backend.live.LiveRoomService rooms;@Autowired com.manliao.backend.media.MediaService media;@Autowired com.manliao.backend.media.MediaJobs jobs;
 final HttpClient http=HttpClient.newHttpClient();int sequence;
 record Reply(int status,JsonNode body){String text(String key){return body.get(key).asString();}}
 record User(String id,String token,String session){}
 @BeforeEach void clean(){db.execute("TRUNCATE admin_users,users,conversations,auth_rate_windows RESTART IDENTITY CASCADE");sequence=1;}
 Reply call(String method,String path,Object body,User user)throws Exception{
  var b=HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+path)).timeout(java.time.Duration.ofSeconds(15));if(user!=null)b.header("Authorization","Bearer "+user.token());if(body!=null)b.header("Content-Type","application/json");
  var r=http.send(b.method(method,body==null?HttpRequest.BodyPublishers.noBody():HttpRequest.BodyPublishers.ofString(json.writeValueAsString(body))).build(),HttpResponse.BodyHandlers.ofString());
  return new Reply(r.statusCode(),r.body().isBlank()?null:json.readTree(r.body()));
 }
 User user()throws Exception{
  var r=call("POST","/auth/register",Map.of("phone","1398100"+String.format("%04d",sequence++),"nickname","账本测试","password","Wallet-test-password"),null);
  assertThat(r.status()).isEqualTo(200);return new User(r.text("user_id"),r.text("access_token"),r.text("session_id"));
 }
 User owner()throws Exception{admins.bootstrap(new com.manliao.backend.admin.AdminDtos.Create("host_owner","Owner-test-password-123","owner","owner"));var r=call("POST","/admin/auth/login",Map.of("username","host_owner","password","Owner-test-password-123"),null);return new User("admin",r.text("access_token"),null);}
 Map<String,Object> payload(java.time.LocalDate date){return new LinkedHashMap<>(Map.of("legal_name","测试用户","id_number","TESTONLY12345678","date_of_birth",date.toString(),"guardian_consent",false,"agreement_accepted",true));}
 Reply submit(User user)throws Exception{return call("POST","/live/host-verification/applications",payload(java.time.LocalDate.of(1990,1,1)),user);}
 String app(Reply r){return r.body().get("applications").get(0).get("id").asString();}
 Reply review(User owner,String app,String decision,boolean gifts)throws Exception{return call("POST","/admin/host-verification/applications/"+app+"/resolve",Map.of("decision",decision,"allow_gifts",gifts,"reason","审核记录"),owner);}
 User host()throws Exception{var a=user();review(owner(),app(submit(a)),"approved",true);return a;}
 String room(User a)throws Exception{var r=call("POST","/live/rooms",Map.of("title","测试直播","category","聊天"),a);assertThat(r.status()).isEqualTo(200);return r.text("id");}
 Map<String,Object> checkInput(){return new LinkedHashMap<>(Map.of("device_id","test-device","camera_permission",true,"microphone_permission",true,"camera_available",true,"microphone_available",true,"network_type","wifi","latency_ms",50,"upload_mbps",10));}
 Reply check(User a,String id)throws Exception{return call("POST","/live/rooms/"+id+"/preflight",checkInput(),a);}
 Reply start(User a,String id,String ticket)throws Exception{return call("POST","/live/rooms/"+id+"/start",Map.of("preflight_ticket",ticket),a);}
 String live(User a)throws Exception{String id=room(a);assertThat(start(a,id,check(a,id).text("ticket")).status()).isEqualTo(200);return id;}
 String cover(User a)throws Exception{var bytes=new java.io.ByteArrayOutputStream();javax.imageio.ImageIO.write(new java.awt.image.BufferedImage(2,2,java.awt.image.BufferedImage.TYPE_INT_RGB),"png",bytes);var r=media.upload(new AuthDtos.Principal(a.id(),a.session()),"image","profile",null,new org.springframework.mock.web.MockMultipartFile("file","cover.png","image/png",bytes.toByteArray()));String id=(String)r.get("id");db.update("UPDATE media_assets SET status='approved' WHERE id=?",id);return id;}
 String coverRoom(User a,String media)throws Exception{String url=db.queryForObject("SELECT url FROM media_assets WHERE id=?",String.class,media);var r=call("POST","/live/rooms",Map.of("title","图片封面","category","聊天","cover_url",url),a);assertThat(r.status()).isEqualTo(200);return r.text("id");}
 void adult(User a){db.update("INSERT INTO gift_safety_settings(user_id,age_status) VALUES(?,'adult') ON CONFLICT(user_id) DO UPDATE SET age_status='adult'",a.id());}
 User viewer(String room)throws Exception{var a=user();adult(a);assertThat(call("POST","/live/rooms/"+room+"/participants/me",null,a).status()).isEqualTo(200);assertThat(call("POST","/wallet/recharge/dev",Map.of("amount",10000,"client_request_id","gift-test-credit"),a).status()).isEqualTo(200);return a;}
 Reply send(User a,String room,String code,int qty,String key)throws Exception{return send(a,room,new LinkedHashMap<>(Map.of("gift_code",code,"quantity",qty,"client_request_id",key)));}
 Reply send(User a,String room,Map<String,Object> body)throws Exception{return call("POST","/live/rooms/"+room+"/gifts",body,a);}
 String confirm(User a,String room,String code,int qty)throws Exception{var r=call("POST","/live/rooms/"+room+"/gift-confirmations",Map.of("gift_code",code,"quantity",qty),a);assertThat(r.status()).isEqualTo(200);return r.text("id");}
 long balance(User a){return db.queryForObject("SELECT balance FROM wallets WHERE user_id=?",Long.class,a.id());}
 int gifts(){return db.queryForObject("SELECT count(*) FROM live_gift_records",Integer.class);}
 @Test void chargeUsesBalancedLedgerAndIntegerSeventyPercent()throws Exception{var h=host();String room=live(h);var a=viewer(room);var r=send(a,room,"coffee",9,"charge-coffee");assertThat(r.status()).isEqualTo(200);assertThat(r.body().get("total_coins").asLong()).isEqualTo(90);assertThat(r.body().get("host_income_coins").asLong()).isEqualTo(63);assertThat(balance(a)).isEqualTo(9910);assertThat(db.queryForObject("SELECT balance FROM coin_accounts WHERE user_id=? AND account_type='host_payable'",Long.class,h.id())).isEqualTo(63);assertThat(db.queryForObject("SELECT sum(amount) FROM coin_ledger_entries WHERE transaction_id=?",Long.class,r.text("billing_transaction_id"))).isZero();assertThat(call("GET","/live/income/summary",null,h).body().get("pending_coins").asLong()).isEqualTo(63);}
 @Test void oneCoinGiftOmitsZeroHostLegAndDefaultQuantityIsOne()throws Exception{var h=host();String room=live(h);var a=viewer(room);var r=send(a,room,Map.of("gift_code","rose","client_request_id","one-coin-gift"));assertThat(r.status()).isEqualTo(200);assertThat(r.body().get("quantity").asInt()).isEqualTo(1);assertThat(r.body().get("host_income_coins").asLong()).isZero();assertThat(balance(a)).isEqualTo(9999);}
 @Test void concurrentDuplicateChargesOnceAndMismatchConflicts()throws Exception{var h=host();String room=live(h);var a=viewer(room);try(var pool=Executors.newVirtualThreadPerTaskExecutor()){var f1=pool.submit(()->send(a,room,"coffee",1,"same-request"));var f2=pool.submit(()->send(a,room,"coffee",1,"same-request"));var r1=f1.get();var r2=f2.get();assertThat(r1.status()).isEqualTo(200);assertThat(r2.text("id")).isEqualTo(r1.text("id"));}assertThat(gifts()).isEqualTo(1);assertThat(balance(a)).isEqualTo(9990);assertThat(send(a,room,"coffee",2,"same-request").status()).isEqualTo(409);}
 @Test void ageDenialPersistsRiskAndNoDebit()throws Exception{var h=host();String room=live(h);var a=viewer(room);for(String age:List.of("unverified","minor")){db.update("UPDATE gift_safety_settings SET age_status=? WHERE user_id=?",age,a.id());assertThat(send(a,room,"rose",1,"age-check-"+age).status()).isEqualTo(403);}assertThat(balance(a)).isEqualTo(10000);assertThat(gifts()).isZero();assertThat(db.queryForObject("SELECT count(*) FROM gift_risk_events WHERE user_id=?",Integer.class,a.id())).isEqualTo(2);}
 @Test void concurrentDailyLimitCannotOverspend()throws Exception{var h=host();String room=live(h);var a=viewer(room);call("PATCH","/live/gift-safety/me",Map.of("daily_limit_coins",15),a);try(var pool=Executors.newVirtualThreadPerTaskExecutor()){var f1=pool.submit(()->send(a,room,"coffee",1,"daily-one"));var f2=pool.submit(()->send(a,room,"coffee",1,"daily-two"));assertThat(List.of(f1.get().status(),f2.get().status())).containsExactlyInAnyOrder(200,409);}assertThat(balance(a)).isEqualTo(9990);assertThat(gifts()).isEqualTo(1);}
 @Test void singleLimitAndHostOrMembershipRulesPreventCharge()throws Exception{var h=host();String room=live(h);var a=viewer(room);call("PATCH","/live/gift-safety/me",Map.of("single_limit_coins",5),a);assertThat(send(a,room,"coffee",1,"single-limit").status()).isEqualTo(409);assertThat(send(h,room,"rose",1,"host-self-gift").status()).isEqualTo(400);call("DELETE","/live/rooms/"+room+"/participants/me",null,a);assertThat(send(a,room,"rose",1,"left-room-gift").status()).isEqualTo(400);call("POST","/live/rooms/"+room+"/participants/me",null,a);db.update("UPDATE live_host_qualifications SET can_receive_gifts=false WHERE user_id=?",h.id());assertThat(send(a,room,"rose",1,"host-gifts-off").status()).isEqualTo(403);assertThat(gifts()).isZero();}
 @Test void confirmationBindsOwnerPriceQuantityAndSingleUse()throws Exception{var h=host();String room=live(h);var a=viewer(room);var b=viewer(room);String c=confirm(a,room,"diamond",1);var payload=new LinkedHashMap<String,Object>(Map.of("gift_code","diamond","quantity",1,"client_request_id","high-value-gift","risk_confirmation_id",c));assertThat(send(b,room,payload).status()).isEqualTo(409);payload.put("quantity",2);assertThat(send(a,room,payload).status()).isEqualTo(409);payload.put("quantity",1);assertThat(send(a,room,payload).status()).isEqualTo(200);assertThat(send(a,room,payload).status()).isEqualTo(200);payload.put("client_request_id","high-value-second");assertThat(send(a,room,payload).status()).isEqualTo(409);assertThat(db.queryForObject("SELECT count(*) FROM gift_risk_events WHERE gift_record_id IS NOT NULL",Integer.class)).isEqualTo(1);}
 @Test void expiredConfirmationAndChangedPriceCannotBeUsed()throws Exception{var h=host();String room=live(h);var a=viewer(room);String c=confirm(a,room,"diamond",1);db.update("UPDATE gift_risk_confirmations SET expires_at=now()-interval '1 second' WHERE id=?",c);assertThat(send(a,room,Map.of("gift_code","diamond","client_request_id","expired-confirm","risk_confirmation_id",c)).status()).isEqualTo(409);c=confirm(a,room,"diamond",1);db.update("UPDATE live_gift_catalog_items SET price_coins=521 WHERE code='diamond'");try{assertThat(send(a,room,Map.of("gift_code","diamond","client_request_id","changed-price","risk_confirmation_id",c)).status()).isEqualTo(409);}finally{db.update("UPDATE live_gift_catalog_items SET price_coins=520 WHERE code='diamond'");}}
 @Test void insufficientFundsDoesNotConsumeConfirmation()throws Exception{var h=host();String room=live(h);var a=user();adult(a);call("POST","/live/rooms/"+room+"/participants/me",null,a);String c=confirm(a,room,"diamond",1);var payload=Map.<String,Object>of("gift_code","diamond","client_request_id","insufficient-gift","risk_confirmation_id",c);assertThat(send(a,room,payload).status()).isEqualTo(403);assertThat(db.queryForMap("SELECT used_at FROM gift_risk_confirmations WHERE id=?",c).get("used_at")).isNull();call("POST","/wallet/recharge/dev",Map.of("amount",600,"client_request_id","after-funds-added"),a);assertThat(send(a,room,payload).status()).isEqualTo(200);}
 @Test void rateLimitCommitsRejectedAttemptAndDuplicateDoesNotCount()throws Exception{var h=host();String room=live(h);var a=viewer(room);for(int i=0;i<10;i++)assertThat(send(a,room,"rose",1,"rapid-gift-"+i).status()).isEqualTo(200);assertThat(send(a,room,"rose",1,"rapid-gift-0").status()).isEqualTo(200);assertThat(send(a,room,"rose",1,"rapid-gift-10").status()).isEqualTo(429);assertThat(gifts()).isEqualTo(10);assertThat(db.queryForObject("SELECT count(*) FROM gift_risk_events WHERE event_type='rapid_gifting'",Integer.class)).isEqualTo(1);}
 @Test void comboLimitExpiryAndCatalogSnapshot()throws Exception{var h=host();String room=live(h);var a=viewer(room);var r=send(a,room,"rose",99,"combo-start");assertThat(r.status()).isEqualTo(200);String combo=r.text("combo_id");assertThat(send(a,room,Map.of("gift_code","rose","quantity",2,"client_request_id","combo-too-many","combo_id",combo)).status()).isEqualTo(409);assertThat(send(a,room,Map.of("gift_code","rose","quantity",1,"client_request_id","combo-last-one","combo_id",combo)).status()).isEqualTo(200);db.update("UPDATE live_gift_records SET combo_expires_at=now()-interval '1 second'");assertThat(send(a,room,Map.of("gift_code","rose","quantity",1,"client_request_id","combo-expired","combo_id",combo)).status()).isEqualTo(409);db.update("UPDATE live_gift_catalog_items SET name='新名字',price_coins=2 WHERE code='rose'");try{var old=send(a,room,"rose",99,"combo-start");assertThat(old.body().get("unit_price").asLong()).isEqualTo(1);assertThat(old.text("gift_name")).isEqualTo("玫瑰");}finally{db.update("UPDATE live_gift_catalog_items SET name='玫瑰',price_coins=1 WHERE code='rose'");}}
 @Test void rankingsRespectConsentAndSelfVisibility()throws Exception{var h=host();String room=live(h);var a=viewer(room);send(a,room,"coffee",1,"ranking-gift");String path="/live/rooms/"+room+"/gift-ranking";assertThat(call("GET",path,null,h).body().get(0).get("sender_id").asString()).isEmpty();assertThat(call("GET",path,null,a).body().get(0).get("sender_id").asString()).isEqualTo(a.id());call("PATCH","/live/gift-safety/me",Map.of("ranking_consent",true),a);assertThat(call("GET",path,null,h).body().get(0).get("sender_id").asString()).isEqualTo(a.id());}
 @Test void maturityMovesIncomeAndAdminReadIsProtected()throws Exception{var h=host();String room=live(h);var a=viewer(room);send(a,room,"coffee",1,"maturity-gift");db.update("UPDATE live_gift_records SET created_at=now()-interval '8 days'");var r=call("GET","/live/income/summary",null,h);assertThat(r.body().get("available_coins").asLong()).isEqualTo(7);assertThat(r.body().get("pending_coins").asLong()).isZero();assertThat(call("GET","/live/income/records?status=available",null,h).body().size()).isEqualTo(1);assertThat(call("GET","/admin/live/rooms/"+room+"/gifts",null,a).status()).isIn(401,403);assertThat(call("GET","/admin/live/rooms/"+room+"/gifts",null,owner()).body().size()).isEqualTo(1);}
 @Test void erasureRetainsFinancialEvidenceAndScrubsLiveData()throws Exception{var h=host();String room=live(h);var a=viewer(room);String c=confirm(a,room,"diamond",1);assertThat(send(a,room,Map.of("gift_code","diamond","client_request_id","erasure-gift","risk_confirmation_id",c)).status()).isEqualTo(200);for(var u:List.of(a,h)){db.update("UPDATE users SET status='deactivation_pending',deactivation_due_at=now()-interval '1 day' WHERE id=?",u.id());assertThat(accounts.eraseDue(u.id())).isTrue();}assertThat(gifts()).isEqualTo(1);assertThat(db.queryForObject("SELECT status FROM live_rooms WHERE id=?",String.class,room)).isEqualTo("closed");assertThat(db.queryForObject("SELECT count(*) FROM live_room_participants",Integer.class)).isZero();assertThat(db.queryForObject("SELECT count(*) FROM gift_risk_confirmations",Integer.class)).isZero();assertThat(db.queryForObject("SELECT details::text FROM gift_risk_events WHERE gift_record_id IS NOT NULL",String.class)).isEqualTo("{}");}
 @Test void databaseFailureRollsBackDebitGiftAndConfirmation()throws Exception{var h=host();String room=live(h);var a=viewer(room);String c=confirm(a,room,"diamond",1);db.execute("ALTER TABLE live_rooms ADD CONSTRAINT fixture_heat_failure CHECK(heat<520)");try{assertThat(send(a,room,Map.of("gift_code","diamond","client_request_id","atomic-failure","risk_confirmation_id",c)).status()).isEqualTo(500);}finally{db.execute("ALTER TABLE live_rooms DROP CONSTRAINT fixture_heat_failure");}assertThat(balance(a)).isEqualTo(10000);assertThat(gifts()).isZero();assertThat(db.queryForMap("SELECT used_at FROM gift_risk_confirmations WHERE id=?",c).get("used_at")).isNull();assertThat(db.queryForObject("SELECT count(*) FROM billing_transactions WHERE transaction_type='gift_charge'",Integer.class)).isZero();}
}