package com.manliao.backend;
import java.net.*;
import java.net.http.*;
import java.util.*;
import java.util.concurrent.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.*;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.support.TransactionTemplate;
import tools.jackson.databind.*;
import com.manliao.backend.billing.*;
import com.manliao.backend.identity.*;
import com.manliao.backend.common.ApiError;
import static org.assertj.core.api.Assertions.*;
@Import(TestcontainersConfiguration.class)
@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT,properties={"app.auth.legacy-registration-enabled=true","app.auth.jwt-secret=isolated-live-tests-secret-at-least-thirty-two-bytes","app.accounts.worker-enabled=false","app.realtime.worker-enabled=false","app.media.derivatives-worker-enabled=false","app.media.jobs-worker-enabled=false","app.media.draft-worker-enabled=false","app.environment=test","app.live.provider=mock","app.live.mock-enabled=true","app.billing.dev-recharge-enabled=true"})
class LiveRoomIntegrationTests {
 @Value("${local.server.port}") int port;
 @Autowired com.manliao.backend.admin.AdminService admins;
 @Autowired JdbcTemplate db;@Autowired ObjectMapper json;@Autowired LedgerService ledger;@Autowired WalletService wallet;@Autowired AccountLifecycleService accounts;@Autowired TransactionTemplate tx;
 @Autowired com.manliao.backend.live.HostVerificationService host;
 @Autowired com.manliao.backend.live.LiveRoomService rooms;@Autowired com.manliao.backend.media.MediaService media;@Autowired com.manliao.backend.media.MediaJobs jobs;
 final HttpClient http=HttpClient.newHttpClient();int sequence;
 record Reply(int status,JsonNode body){String text(String key){return body.get(key).asString();}}
 record User(String id,String token,String session){}
 @BeforeEach void clean(){db.execute("TRUNCATE admin_users,users,conversations,auth_rate_windows RESTART IDENTITY CASCADE");sequence=1;}
 Reply call(String method,String path,Object body,User user)throws Exception{
  var b=HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+path)).timeout(java.time.Duration.ofSeconds(15));if(user!=null)b.header("Authorization","Bearer "+user.token());if(body!=null)b.header("Content-Type","application/json");
  var r=http.send(b.method(method,body==null?HttpRequest.BodyPublishers.noBody():HttpRequest.BodyPublishers.ofString(json.writeValueAsString(body))).build(),HttpResponse.BodyHandlers.ofString());
  return new Reply(r.statusCode(),r.body().isBlank()?null:json.readTree(r.body()));
 }
 User user()throws Exception{
  var r=call("POST","/auth/register",Map.of("phone","1398100"+String.format("%04d",sequence++),"nickname","账本测试","password","Wallet-test-password"),null);
  assertThat(r.status()).isEqualTo(200);return new User(r.text("user_id"),r.text("access_token"),r.text("session_id"));
 }
 User owner()throws Exception{admins.bootstrap(new com.manliao.backend.admin.AdminDtos.Create("host_owner","Owner-test-password-123","owner","owner"));var r=call("POST","/admin/auth/login",Map.of("username","host_owner","password","Owner-test-password-123"),null);return new User("admin",r.text("access_token"),null);}
 Map<String,Object> payload(java.time.LocalDate date){return new LinkedHashMap<>(Map.of("legal_name","测试用户","id_number","TESTONLY12345678","date_of_birth",date.toString(),"guardian_consent",false,"agreement_accepted",true));}
 Reply submit(User user)throws Exception{return call("POST","/live/host-verification/applications",payload(java.time.LocalDate.of(1990,1,1)),user);}
 String app(Reply r){return r.body().get("applications").get(0).get("id").asString();}
 Reply review(User owner,String app,String decision,boolean gifts)throws Exception{return call("POST","/admin/host-verification/applications/"+app+"/resolve",Map.of("decision",decision,"allow_gifts",gifts,"reason","审核记录"),owner);}
 User host()throws Exception{var a=user();review(owner(),app(submit(a)),"approved",true);return a;}
 String room(User a)throws Exception{var r=call("POST","/live/rooms",Map.of("title","测试直播","category","聊天"),a);assertThat(r.status()).isEqualTo(200);return r.text("id");}
 Map<String,Object> checkInput(){return new LinkedHashMap<>(Map.of("device_id","test-device","camera_permission",true,"microphone_permission",true,"camera_available",true,"microphone_available",true,"network_type","wifi","latency_ms",50,"upload_mbps",10));}
 Reply check(User a,String id)throws Exception{return call("POST","/live/rooms/"+id+"/preflight",checkInput(),a);}
 Reply start(User a,String id,String ticket)throws Exception{return call("POST","/live/rooms/"+id+"/start",Map.of("preflight_ticket",ticket),a);}
 String live(User a)throws Exception{String id=room(a);assertThat(start(a,id,check(a,id).text("ticket")).status()).isEqualTo(200);return id;}
 String cover(User a)throws Exception{var bytes=new java.io.ByteArrayOutputStream();javax.imageio.ImageIO.write(new java.awt.image.BufferedImage(2,2,java.awt.image.BufferedImage.TYPE_INT_RGB),"png",bytes);var r=media.upload(new AuthDtos.Principal(a.id(),a.session()),"image","profile",null,new org.springframework.mock.web.MockMultipartFile("file","cover.png","image/png",bytes.toByteArray()));String id=(String)r.get("id");db.update("UPDATE media_assets SET status='approved' WHERE id=?",id);return id;}
 String coverRoom(User a,String media)throws Exception{String url=db.queryForObject("SELECT url FROM media_assets WHERE id=?",String.class,media);var r=call("POST","/live/rooms",Map.of("title","图片封面","category","聊天","cover_url",url),a);assertThat(r.status()).isEqualTo(200);return r.text("id");}
 @Test void categoriesPublicAndRoomsRequireAuthentication()throws Exception{assertThat(call("GET","/live/categories",null,null).body().get("primary").size()).isEqualTo(4);assertThat(call("GET","/live/rooms",null,null).status()).isEqualTo(401);assertThat(call("POST","/live/rooms",Map.of("title","test","category","聊天"),null).status()).isEqualTo(401);}
 @Test void draftOwnerOnlyAndSessionNeverClaimsRealStream()throws Exception{var a=host();var b=user();String id=room(a);assertThat(call("GET","/live/rooms/"+id,null,b).status()).isEqualTo(404);assertThat(call("GET","/live/rooms/"+id+"/stream-session",null,b).status()).isEqualTo(403);var session=call("GET","/live/rooms/"+id+"/stream-session",null,a);assertThat(session.body().get("is_mock").asBoolean()).isTrue();assertThat(session.body().get("push_url").isNull()).isTrue();assertThat(call("GET","/live/rooms",null,b).body().size()).isZero();}
 @Test void qualificationRequiredBeforeCheckOrStart()throws Exception{var a=user();String id=room(a);assertThat(check(a,id).status()).isEqualTo(403);assertThat(call("POST","/live/rooms/"+id+"/start",null,a).status()).isEqualTo(403);}
 @Test void successfulLifecycleChecksTicketAndPresence()throws Exception{var a=host();var b=user();String id=room(a);assertThat(call("POST","/live/rooms/"+id+"/start",null,a).status()).isEqualTo(403);var preflight=check(a,id);assertThat(preflight.status()).isEqualTo(200);assertThat(preflight.body().get("can_start").asBoolean()).isTrue();assertThat(preflight.body().get("requires_confirmation").asBoolean()).isFalse();var started=start(a,id,preflight.text("ticket"));assertThat(started.body().get("online_count").asInt()).isEqualTo(1);assertThat(call("POST","/live/rooms/"+id+"/participants/me",null,b).status()).isEqualTo(200);assertThat(call("POST","/live/rooms/"+id+"/participants/me",null,b).status()).isEqualTo(200);assertThat(call("GET","/live/rooms/"+id,null,b).body().get("online_count").asInt()).isEqualTo(2);assertThat(call("DELETE","/live/rooms/"+id+"/participants/me",null,a).status()).isEqualTo(400);assertThat(call("DELETE","/live/rooms/"+id+"/participants/me",null,b).status()).isEqualTo(200);assertThat(call("POST","/live/rooms/"+id+"/end",null,b).status()).isEqualTo(403);assertThat(call("POST","/live/rooms/"+id+"/end",null,a).body().get("status").asString()).isEqualTo("ended");assertThat(call("GET","/live/rooms/"+id,null,b).status()).isEqualTo(404);assertThat(call("POST","/live/rooms/"+id+"/participants/me",null,b).status()).isEqualTo(400);}
 @Test void failedDeviceOrNetworkGetsNoTicket()throws Exception{var a=host();String id=room(a);for(var change:List.of(Map.of("camera_permission",false),Map.of("microphone_available",false),Map.of("network_type","none"),Map.of("latency_ms",800),Map.of("upload_mbps",0.5))){var p=checkInput();p.putAll(change);var r=call("POST","/live/rooms/"+id+"/preflight",p,a);assertThat(r.status()).isEqualTo(200);assertThat(r.body().get("can_start").asBoolean()).isFalse();assertThat(r.body().get("ticket").isNull()).isTrue();assertThat(r.text("result")).isEqualTo("failed");}}
 @Test void warningRequiresExplicitConfirmation()throws Exception{var a=host();String id=room(a);var p=checkInput();p.put("latency_ms",350);var r=call("POST","/live/rooms/"+id+"/preflight",p,a);assertThat(r.body().get("requires_confirmation").asBoolean()).isTrue();assertThat(r.body().get("ticket").isNull()).isTrue();p.put("user_confirmed_warnings",true);var confirmed=call("POST","/live/rooms/"+id+"/preflight",p,a);assertThat(confirmed.body().get("can_start").asBoolean()).isTrue();assertThat(start(a,id,confirmed.text("ticket")).status()).isEqualTo(200);}
 @Test void ticketsExpireAndBindToRoomAndHost()throws Exception{var a=host();var b=user();String id=room(a),other=room(a);String ticket=check(a,id).text("ticket");assertThat(start(a,other,ticket).status()).isEqualTo(403);assertThat(start(b,id,ticket).status()).isEqualTo(403);db.update("UPDATE live_start_preflights SET expires_at=now()-interval '1 second' WHERE room_id=?",id);assertThat(start(a,id,ticket).status()).isEqualTo(403);}
 @Test void newFailedCheckInvalidatesOldSuccessfulTicket()throws Exception{var a=host();String id=room(a);String ticket=check(a,id).text("ticket");var p=checkInput();p.put("camera_permission",false);call("POST","/live/rooms/"+id+"/preflight",p,a);assertThat(start(a,id,ticket).status()).isEqualTo(403);}
 @Test void concurrentStartOnlyCreatesOneActiveRoom()throws Exception{var a=host();String one=room(a),two=room(a),t1=check(a,one).text("ticket"),t2=check(a,two).text("ticket");try(var pool=Executors.newVirtualThreadPerTaskExecutor()){var f1=pool.submit(()->start(a,one,t1));var f2=pool.submit(()->start(a,two,t2));assertThat(List.of(f1.get().status(),f2.get().status())).containsExactlyInAnyOrder(200,409);}assertThat(db.queryForObject("SELECT count(*) FROM live_rooms WHERE status='live'",Integer.class)).isEqualTo(1);assertThat(db.queryForObject("SELECT count(*) FROM live_start_preflights WHERE consumed_at IS NOT NULL",Integer.class)).isEqualTo(1);}
 @Test void suspensionAfterCheckStillBlocksStart()throws Exception{var a=host();String id=room(a),ticket=check(a,id).text("ticket");call("POST","/admin/host-verification/qualifications/"+a.id()+"/suspend",Map.of("reason","暂停测试"),owner());assertThat(start(a,id,ticket).status()).isEqualTo(403);}
 @Test void kickedMemberCannotRejoinOrChangePresence()throws Exception{var a=host();var b=user();String id=live(a);call("POST","/live/rooms/"+id+"/participants/me",null,b);db.update("UPDATE live_room_participants SET presence_status='kicked' WHERE room_id=? AND user_id=?",id,b.id());assertThat(call("POST","/live/rooms/"+id+"/participants/me",null,b).status()).isEqualTo(403);assertThat(call("DELETE","/live/rooms/"+id+"/participants/me",null,b).status()).isEqualTo(403);}
 @Test void disabledAndProductionMockFailClosed()throws Exception{var a=user();org.springframework.test.util.ReflectionTestUtils.setField(rooms,"mock",false);try{assertThat(call("POST","/live/rooms",Map.of("title","test","category","聊天"),a).status()).isEqualTo(503);}finally{org.springframework.test.util.ReflectionTestUtils.setField(rooms,"mock",true);}org.springframework.test.util.ReflectionTestUtils.setField(rooms,"environment","production");try{assertThat(call("POST","/live/rooms",Map.of("title","test","category","聊天"),a).status()).isEqualTo(503);}finally{org.springframework.test.util.ReflectionTestUtils.setField(rooms,"environment","test");}}
 @Test void contentChangesAfterPreflightCannotStart()throws Exception{var a=host();String id=room(a),ticket=check(a,id).text("ticket");db.update("UPDATE live_rooms SET title='赌博下注' WHERE id=?",id);assertThat(start(a,id,ticket).status()).isEqualTo(403);}
 @Test void coverOwnershipReviewAndDraftRetention()throws Exception{var a=host();var b=user();String asset=cover(a),id=coverRoom(a,asset);assertThat(call("POST","/live/rooms",Map.of("title","x","category","聊天","cover_url","media:"+asset),b).status()).isEqualTo(422);db.update("UPDATE media_assets SET created_at=now()-interval '2 days' WHERE id=?",asset);jobs.reclaimDrafts();assertThat(db.queryForObject("SELECT status FROM media_assets WHERE id=?",String.class,asset)).isEqualTo("approved");String ticket=check(a,id).text("ticket");db.update("UPDATE media_assets SET status='rejected' WHERE id=?",asset);assertThat(start(a,id,ticket).status()).isEqualTo(403);}
 @Test void liveCoverSignedAccessRevokesWhenRoomEnds()throws Exception{var a=host();var b=user();String asset=cover(a),id=coverRoom(a,asset);start(a,id,check(a,id).text("ticket"));var r=call("GET","/live/rooms/"+id,null,b);String url=r.text("cover_url");assertThat(url).startsWith("/media/access/");assertThat(http.send(HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+url)).build(),HttpResponse.BodyHandlers.discarding()).statusCode()).isEqualTo(200);call("POST","/live/rooms/"+id+"/end",null,a);assertThat(http.send(HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+url)).build(),HttpResponse.BodyHandlers.discarding()).statusCode()).isEqualTo(404);}
 @Test void erasureRemovesRoomParticipantsChecksAndCoverReferences()throws Exception{var a=host();var b=user();String id=live(a);call("POST","/live/rooms/"+id+"/participants/me",null,b);db.update("UPDATE users SET status='deactivation_pending',deactivation_due_at=now()-interval '1 day' WHERE id=?",a.id());assertThat(accounts.eraseDue(a.id())).isTrue();assertThat(db.queryForObject("SELECT count(*) FROM live_rooms",Integer.class)).isZero();assertThat(db.queryForObject("SELECT count(*) FROM live_room_participants",Integer.class)).isZero();assertThat(db.queryForObject("SELECT count(*) FROM live_start_preflights",Integer.class)).isZero();}
 @Test void adminPreflightAuditDoesNotExposeTicketHash()throws Exception{var a=host();String id=room(a);check(a,id);var r=call("GET","/admin/live-preflight?room_id="+id,null,owner());assertThat(r.status()).isEqualTo(200);assertThat(r.body().size()).isEqualTo(1);assertThat(r.body().toString()).doesNotContain("ticket_hash");assertThat(r.body().get(0).get("ticket").isNull()).isTrue();assertThat(call("GET","/admin/live-preflight",null,a).status()).isIn(401,403);}
 @Test void networkProbeCountsUtf8BytesAndValidationRejectsInvalidInput()throws Exception{var a=user();var r=call("POST","/live/network-probe",Map.of("payload","测".repeat(1024)),a);assertThat(r.body().get("received_bytes").asInt()).isEqualTo(3072);assertThat(call("POST","/live/network-probe",Map.of("payload","short"),a).status()).isEqualTo(422);assertThat(call("POST","/live/rooms",Map.of("title"," ","category","聊天"),a).status()).isEqualTo(422);}
 @Test void unsupportedContentTypeReturns415InsteadOfInternalError()throws Exception{var a=host();String id=room(a);var r=http.send(HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+"/live/rooms/"+id+"/start")).header("Authorization","Bearer "+a.token()).header("Content-Type","text/plain").POST(HttpRequest.BodyPublishers.ofString("invalid")).build(),HttpResponse.BodyHandlers.ofString());assertThat(r.statusCode()).isEqualTo(415);assertThat(r.body()).doesNotContain("COMMON_INTERNAL_ERROR");}
}